### ISSUE TITLE
The pet follow the cursor in wezterm

### ISSUE THREAD

**Issue by codeDude64** [giusgad/pets.nvim#30] opened 2023-03-22 00:48 UTC
### Description

The pet is on the cursor and it follows it in wezterm terminal.

I tried on konsole but here the pets didn't appear (It's not the topic btw)
I tried on kitty terminal and all works as expected

### Steps to reproduce

1. Open nvim
2. run `:PetsNew`
3. observer

### Screenshots

![image](https://user-images.githubusercontent.com/35637860/226773526-9490c476-7c30-4f08-b4cf-e50defdd6983.png)

**Comment by codeDude64** [comment] 2023-03-22 00:49
Oh and this black square appears even when I setup the `avoid_ statusline` options

**Comment by giusgad** [comment] 2023-03-22 08:19
The cursor issue in WezTerm is something I already knew about, that's why in the reamde I specified that the only terminal that actually works is kitty. The issue is related to either WezTerm's implementation of the kitty graphics protocol, or to how hologram approaches the protocol, either way I can't do anything about it.

The black square is due to the popup using the `"Normal"` highlight group, so you can either change your Normal highlight group to match your bacgkround color or assign it a custom highlight group like so: `popup = { hl = { Normal = "yourhighlightname" }}}`

**Closed by giusgad** 2023-03-22 08:19 UTC
Labels: bug
